---
title: AceDesignznDecor
author: Ace
email: acedesignzndecor@gmail.com
description: AceDesignznDecor - Designing Experiences
baseurl: "/"
url: https://acedesignzndecor.com
logo: "/assets/images/group.png"
incremental: true
sass:
  sass_dir: _sass
  style: compressed
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-watch
- jekyll-sitemap
- jekyll-feed
- jekyll-import
- jekyll-admin
- jekyll-menus
- jekyll-include-cache
